### ISSUE TITLE
Cannot get video file when processing is complete

### ISSUE THREAD

**Issue by palvarez19** [Scholar01/sd-webui-mov2mov#108]
I get the following error when mov2mov has completed processing: 

Start generating .mp4 file██████████████████████████████████████████████████████████| 1584/1584 [16:36<00:00,  2.88it/s]
[ERROR:0@1330.889] global cap_ffmpeg_impl.hpp:3018 open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@1330.889] global cap_ffmpeg_impl.hpp:3093 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@1330.891] global cap.cpp:643 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.1) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'

The generation is complete, the directory::outputs/mov2mov-videos/1698628207.mp4
Total progress: 100%|███████████████████████████████████████████████████████████████| 1584/1584 [16:39<00:00,  1.58it/s]
Traceback (most recent call last):██████████████████████████████████████████████████| 1584/1584 [16:39<00:00,  2.88it/s]
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/home/test/sd4/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1698628207.mp4'

Also, there is no "generate movie mode" as shown on github.

![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/59373436/458042e3-5ccc-4ed7-9d85-fb1876c16543)

**Comment by DavG25** [comment]
Should be fixed now, can you update mov2mov and check if it works for you?

**Comment by palvarez19** [comment]
It does work now thanks! The "generate movie mode" is still missing in the UI, but I was able to create a video.

**Comment by DavG25** [comment]
That's good to hear, I'll close this issue then

As for the 'Generate Movie Mode' missing, from what I can tell it was removed in commit https://github.com/Scholar01/sd-webui-mov2mov/commit/0e0653a99c0a3915e7fe0c831dec30386c16e8cd in favor of automatically using the best available codec on the OS currently running the Web UI

I think we could bring back the 'Generate Movie Mode' with an 'Automatic' option (which does what happens now) and a choice of other codecs, I'll see and maybe make a PR about this
