### ISSUE TITLE
mov2mov tab is missing on WebUI

### ISSUE THREAD

**Issue by ktee95** [Scholar01/sd-webui-mov2mov#92]
Glad that you back to work T_T
i use lastest Vlad''s fork WebUI and manage it via Stability Matrix. 
I just installed the lastest update of mov2mov, but mov2mov tab still not show on UI 
something is missing or conflict with Vlad WebUI?

> 18:47:04-737910 ERROR    Module load:                                          
>                          extensions\sd-webui-mov2mov\scripts\m2m_modnet.py:    
>                          FileNotFoundError                                     
> ┌───────────────────── Traceback (most recent call last) ─────────────────────┐
> │ Z:\StabilityMatrix\Data\Packages\automatic\modules\script_loading.py:18 in  │
> │ load_module                                                                 │
> │                                                                             │
> │   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:      │
> │ > 18 │   │   │   module_spec.loader.exec_module(module)                     │
> │   19 │   │   setup_logging() # reset since scripts can hijaack logging      │
> │ in exec_module:883                                                          │
> │ in _call_with_frames_removed:241                                            │
> │                                                                             │
> │ Z:\StabilityMatrix\Data\Packages\automatic\extensions\sd-webui-mov2mov\scri │
> │ pts\m2m_modnet.py:21 in <module>                                            │
> │                                                                             │
> │    20 models_path = os.path.join(script_path, "models")                     │
> │ >  21 modnet_models = ['none'] + [model for model in os.listdir(models_path │
> │    22                                                                       │
> └─────────────────────────────────────────────────────────────────────────────┘
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 
> 'extensions\\sd-webui-mov2mov\\models'
> 18:47:04-802870 ERROR    Module load:                                          
>                          extensions\sd-webui-mov2mov\scripts\m2m_ui.py:        
>                          ImportError                                           
> ┌───────────────────── Traceback (most recent call last) ─────────────────────┐
> │ Z:\StabilityMatrix\Data\Packages\automatic\modules\script_loading.py:18 in  │
> │ load_module                                                                 │
> │                                                                             │
> │   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:      │
> │ > 18 │   │   │   module_spec.loader.exec_module(module)                     │
> │   19 │   │   setup_logging() # reset since scripts can hijaack logging      │
> │ in exec_module:883                                                          │
> │ in _call_with_frames_removed:241                                            │
> │                                                                             │
> │ Z:\StabilityMatrix\Data\Packages\automatic\extensions\sd-webui-mov2mov\scri │
> │ pts\m2m_ui.py:14 in <module>                                                │
> │                                                                             │
> │    13 import subprocess as sp                                               │
> │ >  14 from modules.ui import Toprow, ordered_ui_categories, create_sampler_ │
> │    15 │   create_override_settings_dropdown, detect_image_size_symbol, resi │
> └─────────────────────────────────────────────────────────────────────────────┘
> ImportError: cannot import name 'Toprow' from 'modules.ui' 
> (Z:\StabilityMatrix\Data\Packages\automatic\modules\ui.py)
> 18:47:04-877702 ERROR    Module load:                                          
>                          extensions\sd-webui-mov2mov\scripts\module_ui_extensio
>                          ns.py: ImportError                                    
> ┌───────────────────── Traceback (most recent call last) ─────────────────────┐
> │ Z:\StabilityMatrix\Data\Packages\automatic\modules\script_loading.py:18 in  │
> │ load_module                                                                 │
> │                                                                             │
> │   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:      │
> │ > 18 │   │   │   module_spec.loader.exec_module(module)                     │
> │   19 │   │   setup_logging() # reset since scripts can hijaack logging      │
> │ in exec_module:883                                                          │
> │ in _call_with_frames_removed:241                                            │
> │                                                                             │
> │ Z:\StabilityMatrix\Data\Packages\automatic\extensions\sd-webui-mov2mov\scri │
> │ pts\module_ui_extensions.py:2 in <module>                                   │
> │                                                                             │
> │    1 # Fix ui library to support custom tabs                                │
> │ >  2 from modules import patches, shared, ui_prompt_styles                  │
> │    3 import modules

**Comment by C4l1b3r** [comment]
![Screenshot_20230923_065754_RVNC Viewer](https://github.com/Scholar01/sd-webui-mov2mov/assets/17440115/26f5580e-dc6d-46c5-b8e2-2bcb024be398)

Same issue

**Comment by Scholar01** [comment]
> ![Screenshot_20230923_065754_RVNC Viewer](https://user-images.githubusercontent.com/17440115/270105579-26f5580e-dc6d-46c5-b8e2-2bcb024be398.jpg)
> 
> Same issue

I just pushed a version

**Comment by yic17** [comment]
Hi, I am using Vlad's SD Next and the Mov2mov tab is not showing up as well. I guess it's not compatible with SD Next? Can you please make them work in the next update?

**Comment by Scholar01** [comment]
@yic17 Can you provide me with the error message?

**Comment by yic17** [comment]
@Scholar01 I think this?

>  Y:\YIC Projects - SD Next 2\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py:14 in <module>                  │
│                                                                                                                     │
│    13 import subprocess as sp                                                                                       │
│ >  14 from modules.ui import Toprow, ordered_ui_categories, create_sampler_and_steps_selection                      │
│    15 │   create_override_settings_dropdown, detect_image_size_symbol, resize_from_to_html, pl                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'Toprow' from 'modules.ui' (Y:\YIC Projects - SD Next 2\automatic\modules\ui.py)
20:14:23-560305 ERROR    Module load: extensions\sd-webui-mov2mov\scripts\module_ui_extensions.py: ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ Y:\YIC Projects - SD Next 2\automatic\modules\script_loading.py:18 in load_module                                   │
│                                                                                                                     │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                              │
│ > 18 │   │   │   module_spec.loader.exec_module(module)                                                             │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging                                              │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ Y:\YIC Projects - SD Next 2\automatic\extensions\sd-webui-mov2mov\scripts\module_ui_extensions.py:2 in <module>     │
│                                                                                                                     │
│    1 # Fix ui library to support custom tabs                                                                        │
│ >  2 from modules import patches, shared, ui_prompt_styles                                                          │
│    3 import modules

**Comment by Scholar01** [comment]
@yic17  I just updated it, can you try it?

**Comment by SamPse** [comment]
> @yic17 I just updated it, can you try it?

Same problem tab is missing on WebUI

**Comment by C4l1b3r** [comment]
@yic17 what version of Stable diffusion are you using?

**Comment by SamPse** [comment]
> @yic17 what version of Stable diffusion are you using?

this one work great : https://github.com/DavG25/sd-webui-mov2mov

**Comment by C4l1b3r** [comment]
![Screenshot_20230924_043945_RVNC Viewer](https://github.com/Scholar01/sd-webui-mov2mov/assets/17440115/57a644b1-fc71-46c7-b501-b62f3b83712b)

**Comment by yic17** [comment]
@Scholar01 Hi, I updated but Mov2mov is still not showing up on the tabs. Here's the new error code:

02:51:09-243129 ERROR    Module load: extensions\sd-webui-mov2mov\scripts\m2m_ui.py: ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ Y:\YIC Projects - SD Next 2\automatic\modules\script_loading.py:18 in load_module                                   │
│                                                                                                                     │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                              │
│ > 18 │   │   │   module_spec.loader.exec_module(module)                                                             │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging                                              │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ Y:\YIC Projects - SD Next 2\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py:10 in <module>                  │
│                                                                                                                     │
│     9 import gradio as gr                                                                                           │
│ >  10 import platform                                                                                               │
│    11 import modules.scripts as scripts                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'patches' from 'modules' (unknown location)

@SamPse I just re-installed Vlad SD Next so it should be the latest version.

**Comment by palvarez19** [comment]
I am having the same issue. I tried deleting the extension folder and reinstall but that didn't work. Here's the error message I get:

*** Error loading script: m2m_util.py
    Traceback (most recent call last):
      File "/home/test/sd3/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/test/sd3/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/test/sd3/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_util.py", line 2, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

**Comment by Scholar01** [comment]
@yic17 @palvarez19 i think i fixed them

**Comment by lg2294001146** [comment]
I'm having the same issue with the latest version
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/130633841/f7264b6a-ff22-4596-b964-f76eead398f3)

**Comment by yic17** [comment]
Yeah, still not working unfortunately. This is the SD version I am using btw @ https://github.com/vladmandic/automatic

For now I'll just stick with Temporal Kit for animations.

**Comment by C4l1b3r** [comment]
> Yeah, still not working unfortunately. This is the SD version I am using btw @ https://github.com/vladmandic/automatic
> 
> For now I'll just stick with Temporal Kit for animations.

Have you tried the non-forked version.

**Comment by zboing** [comment]
> I'm having the same issue with the latest version ![image](https://user-images.githubusercontent.com/130633841/270498827-f7264b6a-ff22-4596-b964-f76eead398f3.png)

I have the same issue. It's because we're using an old sd web ui version and many methods and files are missing, in my case I have version 1.3.2 and the extension has a minimum version 1.5,2 I guess..

**Comment by MrVladH** [comment]
Since the update on September 25, the mov2mov tab disappeared and despite subsequent updates it still does not work. I miss the extension, I hope it can be solved soon.
![Issue mov2mov](https://github.com/Scholar01/sd-webui-mov2mov/assets/122032115/a284e865-104b-4a83-befd-8a3d182f2678)

**Comment by C4l1b3r** [comment]
Just a fyi it works on the non-forked automatic1111 1.6. It actually works better than it did
